### ISSUE TITLE
混淆后，华为8.0有的地方会崩掉

### ISSUE THREAD

**Issue by Blizzard-liu** [850125665/MGson#1]
06-04 10:20:13.162 3416-3416/com.winsky.winto.wintopassenger W/System.err: com.a.a.r: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 25 path $.data
06-04 10:20:13.163 3416-3416/com.winsky.winto.wintopassenger W/System.err:     at com.a.a.b.a.i$a.a(ReflectiveTypeAdapterFactory.java:224)
06-04 10:20:13.164 3416-3416/com.winsky.winto.wintopassenger W/System.err:     at com.a.a.b.a.i$1.a(ReflectiveTypeAdapterFactory.java:129)
        at com.a.a.b.a.i$a.a(ReflectiveTypeAdapterFactory.java:220)
        at com.a.a.f.a(Gson.java:887)
        at com.a.a.f.a(Gson.java:18852)
06-04 10:20:13.165 3416-3416/com.winsky.winto.wintopassenger W/System.err:     at com.winsky.winto.wintopassenger.http.c.a.a(ConvertGson.java:93)
        at com.winsky.winto.wintopassenger.http.a.b.a(JsonCallback.java:103)
        at com.c.a.b.a.a$1.a(BaseCachePolicy.java:163)
06-04 10:20:13.166 3416-3416/com.winsky.winto.wintopassenger W/System.err:     at okhttp3.RealCall$AsyncCall.b(RealCall.java:141)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
06-04 10:20:13.167 3416-3416/com.winsky.winto.wintopassenger W/System.err:     at java.lang.Thread.run(Thread.java:784)
06-04 10:20:13.168 3416-3416/com.winsky.winto.wintopassenger W/System.err: Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 25 path $.data
        at com.a.a.d.a.c(JsonReader.java:385)
06-04 10:20:13.169 3416-3416/com.winsky.winto.wintopassenger W/System.err:     at com.a.a.b.a.i$a.a(ReflectiveTypeAdapterFactory.java:213)
    	... 12 more
    com.a.a.r: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 25 path $.data
        at com.a.a.b.a.i$a.a(ReflectiveTypeAdapterFactory.java:224)
06-04 10:20:13.170 3416-3416/com.winsky.winto.wintopassenger W/System.err:     at com.a.a.b.a.i$1.a(ReflectiveTypeAdapterFactory.java:129)
        at com.a.a.b.a.i$a.a(ReflectiveTypeAdapterFactory.java:220)
        at com.a.a.f.a(Gson.java:887)
        at com.a.a.f.a(Gson.java:18852)
06-04 10:20:13.171 3416-3416/com.winsky.winto.wintopassenger W/System.err:     at com.winsky.winto.wintopassenger.http.c.a.a(ConvertGson.java:93)
        at com.winsky.winto.wintopassenger.http.a.b.a(JsonCallback.java:103)
        at com.c.a.b.a.a$1.a(BaseCachePolicy.java:163)
06-04 10:20:13.171 3416-3416/com.winsky.winto.wintopassenger W/System.err:     at okhttp3.RealCall$AsyncCall.b(RealCall.java:141)
06-04 10:20:13.172 3416-3416/com.winsky.winto.wintopassenger W/System.err:     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:784)
06-04 10:20:13.173 3416-3416/com.winsky.winto.wintopassenger W/System.err: Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 25 path $.data
        at com.a.a.d.a.c(JsonReader.java:385)
        at com.a.a.b.a.i$a.a(ReflectiveTypeAdapterFactory.java:213)
    	... 12 more
06-04 10:20:13.178 3416-3436/com.winsky.winto.wintopassenger W/libEGL: EGLNativeWindowType 0xc4522808 disconnect failed
06-04 10:20:13.191 3416-3416/com.winsky.winto.wintopassenger W/InputMethodManager: startInputReason = 1
06-04 10:20:42.139 3416-3416/com.winsky.winto.wintopassenger W/InputMethodManager: startInputReason = 8
06-04 10:21:12.542 3416-3436/com.winsky.winto.wintopassenger W/libEGL: EGLNativeWindowType 0xdf32a808 disconnect failed

**Comment by Blizzard-liu** [comment]
{
  "data": {
    "actVech": {
      "addPrice": 0.6,
      "addPriceMile": 0.6,
      "bespeakPrice": 0,
      "currLowestCons": 0,
      "durationPrice": 0.3,
      "mileagePrice": 1.5,
      "peakAddMile": null,
      "peakAddPrice": null,
      "peakBeginEnd": "",
      "peakBeginTime": "",
      "preLowestCons": 0,
      "startMile": 3,
      "startPrice": 8
    },
    "bespeakVech": {
      "addPrice": 0.6,
      "addPriceMile": 0.6,
      "bespeakPrice": 0,
      "currLowestCons": 0,
      "durationPrice": 0.3,
      "mileagePrice": 1.5,
      "peakAddMile": null,
      "peakAddPrice": null,
      "peakBeginEnd": "",
      "peakBeginTime": "",
      "preLowestCons": 0,
      "startMile": 3,
      "startPrice": 8
    }
  }
}

**Comment by Blizzard-liu** [comment]
大神 在线等回复

**Comment by wilson-1024** [comment]
@Blizzard-liu  看错误好像是没用到自定义adapter，请问混淆前可以用吗，8.0以下的机器混淆后出现问题吗？

**Comment by Blizzard-liu** [comment]
混淆前没问题 ，华为6.0混淆后也没问题

**Comment by wilson-1024** [comment]
@Blizzard-liu 您好，在混淆文件加下-keep class com.google.**{*;}试试

**Comment by Blizzard-liu** [comment]
可以了，非常感谢，你咋找到原因的
