### ISSUE TITLE
混淆规则是？

### ISSUE THREAD

**Issue by zp-techie** [850125665/MGson#3]
混淆后的release和不用mgson是一样的。所以烦请提供一下混淆规则

**Comment by wilson-1024** [comment]
-keep class com.google.**{*;}
-keepclassmembers class * implements java.io.Serializable {
    static final long serialVersionUID;
    private static final java.io.ObjectStreamField[] serialPersistentFields;
    private void writeObject(java.io.ObjectOutputStream);
    private void readObject(java.io.ObjectInputStream);
    java.lang.Object writeReplace();
    java.lang.Object readResolve();
}
-keepattributes Signature
-keep class sun.misc.Unsafe { *; }

**Comment by zp-techie** [comment]
已解决，非常感谢
